import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

// Middleware
app.use(cors());
app.use(express.json());


// =====================================================
// HOME / HEALTH CHECK
// =====================================================

app.get("/", (req, res) => {
  res.json({
    success: true,
    message: "SkillBridge AI Backend is running",
  });
});


// =====================================================
// AI PROPOSAL GENERATION
// =====================================================

app.post("/api/ai/proposal", async (req, res) => {
  try {
    const { student, project } = req.body;

    if (!student || !project) {
      return res.status(400).json({
        success: false,
        message: "Student and project details are required.",
      });
    }

    const studentName = student.name || "Student";

    const skills = Array.isArray(student.skills)
      ? student.skills.join(", ")
      : student.skills || "Not specified";

    const projectTitle =
      project.title || "Freelance Project";

    const projectDescription =
      project.description ||
      "No project description provided.";

    const requiredSkills = Array.isArray(project.requiredSkills)
      ? project.requiredSkills.join(", ")
      : project.requiredSkills || "Not specified";

    const budget = project.budget || "Not specified";


    const prompt = `
You are the proposal-generation assistant for SkillBridge AI,
a student freelance marketplace.

Your task is to write a professional and natural project proposal
for a student applying to the given freelance project.

STUDENT INFORMATION:
Name: ${studentName}
Skills: ${skills}

PROJECT INFORMATION:
Title: ${projectTitle}
Description: ${projectDescription}
Required Skills: ${requiredSkills}
Budget: ${budget}

IMPORTANT RULES:

1. Use the student's name only if it is necessary.
2. NEVER invent or change the student's name.
3. NEVER use a different person's name.
4. NEVER invent work experience.
5. NEVER invent previous clients, companies, certifications,
   awards, achievements, portfolio links, or case studies.
6. NEVER create fake statistics or performance results.
7. NEVER add placeholders such as [insert text], [Link],
   <portfolio link>, or similar.
8. Mention only the skills actually provided in the student information.
9. Connect the student's listed skills to the project's requirements.
10. Explain briefly why the student is suitable for this project.
11. Show genuine interest in completing the project.
12. Keep the proposal concise, professional, and suitable for
    a student freelancer.
13. Do not make unrealistic promises.
14. Do not include a subject line.
15. Do not include "Best regards", a signature, or any invented name.
16. Do not mention that the proposal was generated by AI.
17. Return ONLY the proposal body.
18. Do not include greetings such as "Hello" or "Dear Client".
19. Keep the proposal between approximately 80 and 150 words.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
    });

    const proposal = response.text?.trim();

    if (!proposal) {
      return res.status(500).json({
        success: false,
        message: "AI did not return a proposal.",
      });
    }

    return res.status(200).json({
      success: true,
      proposal,
    });

  } catch (error) {
    console.error("AI Proposal Error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to generate AI proposal.",
      error: error.message,
    });
  }
});


// =====================================================
// AI PROJECT / SKILL RECOMMENDATION
// =====================================================

app.post("/api/ai/recommendation", async (req, res) => {
  try {
    const { student, project } = req.body;

    if (!student || !project) {
      return res.status(400).json({
        success: false,
        message: "Student and project details are required.",
      });
    }

    const studentSkills = Array.isArray(student.skills)
      ? student.skills.join(", ")
      : student.skills || "Not specified";

    const projectTitle =
      project.title || "Freelance Project";

    const projectDescription =
      project.description ||
      "No project description provided.";

    const requiredSkills = Array.isArray(project.requiredSkills)
      ? project.requiredSkills.join(", ")
      : project.requiredSkills || "Not specified";


    const prompt = `
You are the AI recommendation assistant for SkillBridge AI,
a student freelance marketplace.

Your task is to analyze whether a freelance project is suitable
for a student based only on the student's listed skills and
the project's requirements.

STUDENT INFORMATION:
Skills: ${studentSkills}

PROJECT INFORMATION:
Title: ${projectTitle}
Description: ${projectDescription}
Required Skills: ${requiredSkills}

IMPORTANT RULES:

1. Compare the student's skills with the project's required skills.
2. Identify the skills that match.
3. Identify important required skills that are missing, if any.
4. Give a clear recommendation about whether the project is a
   good match for the student.
5. Do not invent any student skills.
6. Do not invent work experience, certifications, achievements,
   clients, companies, or qualifications.
7. Do not make assumptions about skills that are not listed.
8. If most required skills match, clearly state that the project
   is a good match.
9. If only some skills match, clearly mention the skill gap.
10. If there is very little or no match, clearly state that the
    project may not be the best match.
11. Keep the recommendation concise and easy for a student to understand.
12. Do not mention that the recommendation was generated by AI.
13. Return only the recommendation text.
14. Do not use headings such as "Recommendation:".
15. Keep the response between approximately 50 and 100 words.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
    });

    const recommendation = response.text?.trim();

    if (!recommendation) {
      return res.status(500).json({
        success: false,
        message: "AI did not return a recommendation.",
      });
    }

    return res.status(200).json({
      success: true,
      recommendation,
    });

  } catch (error) {
    console.error("AI Recommendation Error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to generate AI recommendation.",
      error: error.message,
    });
  }
});


// =====================================================
// START SERVER
// =====================================================

app.listen(PORT, () => {
  console.log(
    `SkillBridge AI Backend running on port ${PORT}`
  );
});